name: "Hello Actions"
description: "Greet someone"
author: "576810415@qq.com"

inputs:
    MY_NAME:
        description: "Who to greet"
        required: true
        default: "World"

runs:
    using: "docker"
    image: "dockerfile"

branding:
    icon: "mic"
    color: "purple"
